### ISSUE TITLE
Trying to run speed complainer here on RaspberryPi and receiving error on start

### ISSUE THREAD

**Issue by gkasica** [james-atkinson/speedcomplainer#12]
Have the latest code I believe from the GitHub download and have tried both methods of running the program here after configuration:

python speedcomplainer.py

Or to run in the background:

 python speedcomplainer.py > /dev/null &

and both yield
@mercury:~/speedcomplainer# python speedcomplainer.py  
Traceback (most recent call last):
  File "speedcomplainer.py", line 5, in <module>
    import daemon
ImportError: No module named daemon
@mercury:~/speedcomplainer#  python speedcomplainer.py > /dev/null &
[1] 22184

@mercury:~/speedcomplainer# Traceback (most recent call last):
  File "speedcomplainer.py", line 5, in <module>
    import daemon
ImportError: No module named daemon
[1]+  Exit 1                  python speedcomplainer.py >

I.m not a python programmer so I have no idea how to fix this issue can you assist?
Attached is my config.json file.

 I have AT&T Uverse at 18MB/sec inbound.
Thank you very much for you help.
George Kasica
gkasica@netwrx1.com

[config.zip](https://github.com/james-atkinson/speedcomplainer/files/222666/config.zip)

**Comment by DarthKeizer** [comment]
use the following codes first:
sudo pip install daemon
sudo pip install python-twitter

Your error is that you do not have the daemon package installed

**Comment by gkasica** [comment]
I tried that based on other messages in the list

Here’s what I get:

~/speedcomplainer# pip install daemon

-bash: pip: command not found

root@mercury:~/speedcomplainer# apt-get install pip

Reading package lists... Done

Building dependency tree       

Reading state information... Done

E: Unable to locate package pip

And yes to answer the second email and not clutter up with multiple mails that is the entire error message cut and pate from the system.

**Comment by DarthKeizer** [comment]
It is a package, so run it it another terminal. What happens?

also did you do: sudo apt-get install daemon ?

**Comment by gkasica** [comment]
I installed daemon but still get similar results as shown below - install of dEmon and result all shown:

root@mercury:~/speedcomplainer# apt-get install daemon
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following NEW packages will be installed:
  daemon
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 80.9 kB of archives.
After this operation, 218 kB of additional disk space will be used.
Get:1 http://mirrordirector.raspbian.org/raspbian/ wheezy/main daemon armhf 0.6.4-1 [80.9 kB]
Fetched 80.9 kB in 0s (92.2 kB/s)
Selecting previously unselected package daemon.
(Reading database ... 90314 files and directories currently installed.)
Unpacking daemon (from .../daemon_0.6.4-1_armhf.deb) ...
Processing triggers for man-db ...
Setting up daemon (0.6.4-1) ...
root@mercury:~/speedcomplainer#  python speedcomplainer.py > /dev/null &  
[1] 5597
root@mercury:~/speedcomplainer# Traceback (most recent call last):
  File "speedcomplainer.py", line 5, in <module>
    import daemon
ImportError: No module named daemon

[1]+  Exit 1                  python speedcomplainer.py > /dev/null

---

George R. Kasica

**Comment by virtadpt** [comment]
You need to install Python's daemon module:

```
sudo apt-get install -y python-daemon
```

**Comment by gkasica** [comment]
OK that’s fixed now I’m seeing this…hate to keep posting these but I’m not a python programmer

root@mercury:~/speedcomplainer# python speedcomplainer.py

Traceback (most recent call last):

  File "speedcomplainer.py", line 8, in <module>

```
import twitter
```

ImportError: No module named twitter

**Comment by virtadpt** [comment]
I think there you've got a problem, but it's not insurmountable.  You'll have to set up a virtualenv and install the Twitter Python module into it.  I can walk you through the process if you like.

**Comment by gkasica** [comment]
So this can’t be run in the standard OS environment then?

If you’re willing to sure.

Can I install the twitter python module into the regular OS Environment on the Raspberry OS?

**Comment by virtadpt** [comment]
It can be.  Let me explain, because virtualenvs are not the same as virtual machines:

Python has the notion of virtualenvs, or isolated Python environments which allow you to install Python modules and utilities such that they aren't available to the entire system, just the context of a single application.  This lets you easily run applications which are written using Python 2 and 3 and even conflicting versions of Python modules simultaneously.  Here's how you set one up:

First, install virtualenv and pip (which you'll use to install Python modules): `sudo apt-get install -y python-virtualenv python-pip`

cd into the speedcomplainer/ repository and create a virtualenv: `virtualenv env`

virtualenv will set up a directory structure inside of the repo called env/ and make a bunch of symlinks.  Now activate it: `. env/bin/activate`

Now your shell is using the Python virtual environment you just created and not the systemwide one.  Install the Twitter module (which goes into the virtualenv): `pip install twitter`

Try running speedcomplainer.py again.

**Comment by gkasica** [comment]
So do I need to pull the entire git repository down to the raspberry to make it work or is the zip enough? And if the entire repo how would I do that - again not a git expert here. 

---

George R. Kasica

**Comment by engFelipeMonteiro** [comment]
For thoses who cant install,  is my tutorial to run.

sudo pip install daemon
sudo pip install twitter
sudo apt-get install speedtest-cli
sudo ln -s /usr/bin/speedtest-cli  /usr/local/bin/speedtest-cli
