### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by andysom25** [james-atkinson/speedcomplainer#15]
Got everything set up and now this is what I'm getting when I run the script:

```
 python speedcomplainer.py
======================================
 Starting Speed Complainer!
 Lets get noisy!
======================================
sh: 1: /usr/local/bin/speedtest-cli: not found
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "speedcomplainer.py", line 99, in run
    speedTestResults = self.doSpeedTest()
  File "speedcomplainer.py", line 116, in doSpeedTest
    downloadResult = resultSet[1]
IndexError: list index out of range

```

Help ?

**Comment by engFelipeMonteiro** [comment]
Its happens when the speedtest return a error and can't split correctly.

**Comment by elzach** [comment]
Just got this same error
Python 2.7 too @andysom25 did you find a solution?

**Comment by tcwatson** [comment]
I just installed this and am getting the same error... anyone ever fix it?

Edit: just realized, the first line of the error says sh: 1: /usr/local/bin/speedtest-cli: not found

To fix, do:
pip install speedtest-cli
