### ISSUE TITLE
Issue with Twitter Integration

### ISSUE THREAD

**Issue by tannerhearne** [james-atkinson/speedcomplainer#4]
Hey @james-atkinson,

I am getting the following exception in the cli when I run the python script locally:

``` bash
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "speedcomplainer.py", line 99, in run
    self.tweetResults(speedTestResults)
  File "speedcomplainer.py", line 137, in tweetResults
    api = twitter.Api(consumer_key=self.config['twitter']['twitterConsumerKey'],
AttributeError: 'module' object has no attribute 'Api'
```

And here are lines 130 through 146 of my file (I have added a Twilio integration so my file has a few extr lines in it.)

``` python
def tweetResults(self, speedTestResults):
    print("Tweeting results.")
    thresholdMessages = self.config['tweetThresholds']
    message = None
    for (threshold, messages) in thresholdMessages.items():
        threshold = float(threshold)
        if speedTestResults['downloadResult'] < threshold:
            message = messages[random.randint(0, len(messages) - 1)].replace('{tweetTo}', self.config['tweetTo']).replace('{internetSpeed}', self.config['internetSpeed']).replace('{downloadResult}', str(speedTestResults['downloadResult']))

    if message:
        # >>>>>>> Here is where the error is occurring.
        api = twitter.Api(consumer_key=self.config['twitter']['twitterConsumerKey'],
                        consumer_secret=self.config['twitter']['twitterConsumerSecret'],
                        access_token_key=self.config['twitter']['twitterToken'],
                        access_token_secret=self.config['twitter']['twitterTokenSecret'])

        if api:
            status = api.PostUpdate(message)
```

Any ideas?

Thanks,
@tannerhearne

**Comment by ghost** [comment]
Same issue.

**Comment by manid** [comment]
Make sure you are using python-twitter module, not just the "twitter" one.

pip uninstall twitter
pip install python-twitter

**Comment by tannerhearne** [comment]
Perfect!  Thank you @manid !

**Comment by DarthKeizer** [comment]
Worked for me too, thanks @manid :)
